Repository GeyserMC/Geyser, pull requests merged in 2020-09, with the labels that each got.

#574 Non-full-chunk support
  .gitignore
  bootstrap/spigot/pom.xml
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotPlugin.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/world/GeyserSpigotWorldManager.java
  bootstrap/spigot/src/main/resources/biomes.json
  connector/src/main/java/org/geysermc/connector/network/session/cache/ChunkCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaChunkDataTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/GeyserWorldManager.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/WorldManager.java
  connector/src/main/java/org/geysermc/connector/utils/ChunkUtils.java
Labels: Feature

#1237 [Android] Remove usage of MCProtocolLib Base64 in SkinUtils + more
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
Labels: Optimization

#1076 Add support for manually supplying Bedrock resource packs
  .gitignore
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/network/UpstreamPacketHandler.java
  connector/src/main/java/org/geysermc/connector/utils/FileUtils.java
  connector/src/main/java/org/geysermc/connector/utils/MathUtils.java
  connector/src/main/java/org/geysermc/connector/utils/ResourcePack.java
  connector/src/main/java/org/geysermc/connector/utils/ResourcePackManifest.java
  connector/src/main/resources/config.yml
Labels: Feature

#1286 Scoreboard: Fix various issues
  connector/src/main/java/org/geysermc/connector/scoreboard/Objective.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Scoreboard.java
Labels: Bugfix

#1348 Fix gamemodes not fully applying on server switch
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaNotifyClientTranslator.java
Labels: Bugfix, Needs Testing
