Repository GeyserMC/Geyser, pull requests merged in 2020-10, with the labels that each got.

#1355 Add support for fishing rods pulling Bedrock players
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityStatusTranslator.java
Labels: Feature

#1370 Fix fire being punched in all directions
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/BlockUtils.java
Labels: Bugfix

#1353 BedrockMobEquipmentTranslator: Don't change item slot if already on that slot
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockMobEquipmentTranslator.java
Labels: Bugfix

#1359 Make crossbows prettier
  connector/src/main/java/org/geysermc/connector/entity/living/monster/raid/PillagerEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/CrossbowTranslator.java
Labels: Feature

#1369 Fix bucket interactions on creative mode
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/sound/block/BucketSoundInteractionHandler.java
Labels: Bugfix

#1398 Don't use wrapper objects for positions in ChunkCache
  connector/src/main/java/org/geysermc/connector/network/session/cache/ChunkCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaUnloadChunkTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/GeyserWorldManager.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/chunk/ChunkPosition.java
  connector/src/main/java/org/geysermc/connector/utils/ChunkUtils.java
Labels: Optimization

#1396 fix some NPEs caused by race conditions in chunk conversion
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaChunkDataTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/GeyserWorldManager.java
Labels: Optimization

#1397 Don't use the general thread pool to run an async method
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerListEntryTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
Labels: Optimization

#1358 Update to support ViaVersion 3.2.0
  bootstrap/spigot/pom.xml
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotPlugin.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/world/GeyserSpigotWorldManager.java
Labels: Dependency, Waiting For Minecraft Update

#1195 Bedrock <-> Bedrock skin display fix
  connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
Labels: Bugfix, Needs Testing
