Repository GeyserMC/Geyser, pull requests merged in 2020-08, with the labels that each got.

#680 Fix Skin Caching and Fix Skin Restorer
  .gitignore
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockSetLocalPlayerAsInitializedTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerListEntryTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/spawn/JavaSpawnPlayerTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
  connector/src/main/resources/config.yml
Labels: Bugfix, Work in Progress

#781 Change scoreboard errors to debug only
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaTeamTranslator.java
Labels: Optimization

#1035 Add support for client side settings
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/world/GeyserSpigotWorldManager.java
  connector/pom.xml
  connector/src/main/java/org/geysermc/connector/bootstrap/GeyserBootstrap.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/UpstreamPacketHandler.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/WorldCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockServerSettingsRequestTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/BedrockEntityEventTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockEmoteTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockInteractTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/world/BedrockLevelSoundEventTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDifficultyTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaJoinGameTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityStatusTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerAbilitiesTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaDisplayScoreboardTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaScoreboardObjectiveTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaTeamTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaUpdateScoreTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaNotifyClientTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaUpdateTimeTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/GeyserWorldManager.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/WorldManager.java
  connector/src/main/java/org/geysermc/connector/utils/GameRule.java
  connector/src/main/java/org/geysermc/connector/utils/SettingsUtils.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
Labels: Feature, Upstream, Work in Progress

#1113 Fix Shulker color and open state
  connector/src/main/java/org/geysermc/connector/entity/living/monster/ShulkerEntity.java
Labels: Bugfix

#1108 Fix dust particles type
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaSpawnParticleTranslator.java
Labels: Bugfix

#1118 Fix quotes breaking formatted message strings
  connector/src/main/java/org/geysermc/connector/utils/LanguageUtils.java
Labels: Bugfix

#1188 Implement (hopefully) temporary dimension switching fix
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaChunkDataTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaSpawnPositionTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/ChunkUtils.java
  connector/src/main/java/org/geysermc/connector/utils/DimensionUtils.java
Labels: Bugfix

#1189 Add shulker box item tooltip translating
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/NbtItemStackTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/BasicItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/BookPagesTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/CrossbowTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/EnchantedBookTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/EnchantmentTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/FireworkTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/LeatherArmorTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/MapItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/ShulkerBoxItemTranslator.java
Labels: Feature

#1181 Translate client-computed recipes
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/RecipeRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/FireworkTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDeclareRecipesTranslator.java
Labels: Feature

#1199 Fix reflections relocation
  bootstrap/bungeecord/pom.xml
  bootstrap/spigot/pom.xml
  bootstrap/sponge/pom.xml
  bootstrap/velocity/pom.xml
Labels: Bugfix

#1166 Scoreboard improvements
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeConfiguration.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeLogger.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeePlugin.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotConfiguration.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotLogger.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeLogger.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongePlugin.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneConfiguration.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneLogger.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityConfiguration.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityLogger.java
  connector/src/main/java/org/geysermc/connector/FloodgateKeyLoader.java
  connector/src/main/java/org/geysermc/connector/GeyserLogger.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/session/UpstreamSession.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/WorldCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaScoreboardObjectiveTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaTeamTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaUpdateScoreTranslator.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Objective.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Score.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Scoreboard.java
  connector/src/main/java/org/geysermc/connector/scoreboard/ScoreboardUpdater.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Team.java
  connector/src/main/resources/config.yml
Labels: Optimization

#1206 Tweaks to support Android
  connector/pom.xml
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
  connector/src/main/java/org/geysermc/connector/command/defaults/StopCommand.java
  connector/src/main/java/org/geysermc/connector/common/PlatformType.java
  connector/src/main/java/org/geysermc/connector/network/translators/PacketTranslatorRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/sound/SoundHandlerRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/BlockTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/entity/BlockEntityTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/FileUtils.java
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
  connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
Labels: Bugfix, Feature
