Repository GeyserMC/Geyser, pull requests merged in 2020-05, with the labels that each got.

#560 Fix banner items loosing patterns in inventory
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/BannerTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/entity/BannerBlockEntityTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/ItemUtils.java
Labels: PR: Feature

#561 Fixed unusable space being off by 1
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/updater/ChestInventoryUpdater.java
Labels: PR: Bugfix

#567 Leash fixes
  connector/src/main/java/org/geysermc/connector/entity/LeashKnotEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityAttachTranslator.java
Labels: PR: Bugfix, PR: Feature

#569 Add air bubble UI support
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
Labels: PR: Feature

#580 Fixed fishing rod lines not connecting to other players
  connector/src/main/java/org/geysermc/connector/entity/FishingHookEntity.java
Labels: PR: Bugfix

#572 Added map icons
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/MapItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaMapDataTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/BedrockMapIcon.java
  connector/src/main/java/org/geysermc/connector/utils/MapColor.java
Labels: PR: Feature

#568 Add enchantment table book visual on chunk load
  connector/src/main/java/org/geysermc/connector/utils/BlockEntityUtils.java
Labels: PR: Feature

#587 Added mob spawner block entity data
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/entity/SpawnerBlockEntityTranslator.java
Labels: Feature

#586 Add some elder guardian properties
  connector/src/main/java/org/geysermc/connector/entity/living/monster/ElderGuardianEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaNotifyClientTranslator.java
Labels: Feature

#552 Add firework boost for elytras!
  connector/src/main/java/org/geysermc/connector/entity/FireworkEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
Labels: Feature, Under Review

#584 Added a docker container IP warning
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
  connector/src/main/java/org/geysermc/connector/utils/DockerCheck.java
Labels: Feature, Needs Testing

#609 Fixed trident display and some arrow related cleanup
  connector/src/main/java/org/geysermc/connector/entity/AbstractArrowEntity.java
  connector/src/main/java/org/geysermc/connector/entity/TippedArrowEntity.java
  connector/src/main/java/org/geysermc/connector/entity/TridentEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
Labels: Bugfix

#608 Fix mapping for Burning Skull painting type
  connector/src/main/java/org/geysermc/connector/utils/PaintingType.java
Labels: Bugfix

#598 Add option for disabling command suggestions; add config version
  bootstrap/bukkit/src/main/java/org/geysermc/platform/bukkit/GeyserBukkitConfiguration.java
  bootstrap/bukkit/src/main/java/org/geysermc/platform/bukkit/GeyserBukkitPlugin.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeConfiguration.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeePlugin.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongePlugin.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneConfiguration.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityConfiguration.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityPlugin.java
  connector/src/main/java/org/geysermc/connector/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDeclareCommandsTranslator.java
  connector/src/main/resources/config.yml
Labels: Client Workaround

#611 Fix /geyser offhand command on Bukkit
  connector/src/main/java/org/geysermc/connector/command/defaults/OffhandCommand.java
Labels: Bugfix

#597 Fix painting rotation
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityHeadLookTranslator.java
Labels: Bugfix, Needs Testing

#615 Add optional workaround for >Y128 Nether building
  bootstrap/bukkit/src/main/java/org/geysermc/platform/bukkit/GeyserBukkitConfiguration.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeConfiguration.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneConfiguration.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityConfiguration.java
  connector/src/main/java/org/geysermc/connector/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
  connector/src/main/java/org/geysermc/connector/utils/DimensionUtils.java
  connector/src/main/resources/config.yml
Labels: Client Workaround

#539 Adds skin ears from MinecraftCapes.co.uk + Clientside linked account skins + Elytra textures
  bootstrap/bukkit/src/main/java/org/geysermc/platform/bukkit/GeyserBukkitConfiguration.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeConfiguration.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneConfiguration.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityConfiguration.java
  connector/src/main/java/org/geysermc/connector/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerListEntryTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java
  connector/src/main/java/org/geysermc/connector/utils/SkinUtils.java
  connector/src/main/resources/bedrock/skin/geometry.humanoid.ears.json
  connector/src/main/resources/bedrock/skin/geometry.humanoid.earsSlim.json
  connector/src/main/resources/bedrock/skin/skin_alex.png
  connector/src/main/resources/config.yml
Labels: Feature, Needs Testing

#575 Add players able to sleep in beds
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaBlockChangeTranslator.java
Labels: Bugfix

#579 Fireworks!
  connector/src/main/java/org/geysermc/connector/entity/FireworkEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/FireworkTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/FireworkColor.java
Labels: Feature, Needs Testing

#589 Merge entity mounts branch to master
  connector/src/main/java/org/geysermc/connector/entity/BoatEntity.java
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/MinecartEntity.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/entity/attribute/AttributeType.java
  connector/src/main/java/org/geysermc/connector/entity/living/animal/horse/AbstractHorseEntity.java
  connector/src/main/java/org/geysermc/connector/entity/living/animal/horse/HorseEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/EntityCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockAnimateTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInteractTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockMoveEntityAbsoluteTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockPlayerInputTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityPositionRotationTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityPropertiesTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaVehicleMoveTranslator.java
Labels: Feature, Needs Testing

#633 Check if firework item explosions tag is null (corresponding entity fix)
  connector/src/main/java/org/geysermc/connector/entity/FireworkEntity.java
Labels: Bugfix

#590 Added Crossbow nbt translator
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/CrossbowTranslator.java
Labels: Feature

#650 Fixed some fireworks colors and NPE of there is no NBT
  connector/src/main/java/org/geysermc/connector/entity/FireworkEntity.java
  connector/src/main/java/org/geysermc/connector/utils/FireworkColor.java
Labels: Bugfix

#660 Fix entities stacking on top of each other when mounted
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntitySetPassengersTranslator.java
Labels: Bugfix

#681 Add byte conversion to allow int NBT values for Fireworks
  connector/src/main/java/org/geysermc/connector/entity/FireworkEntity.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/FireworkTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/MathUtils.java
Labels: Bugfix

#688 Fix relative teleports
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerPositionRotationTranslator.java
Labels: Bugfix

#691 Implement translator for AdventureSettingsPacket
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockAdventureSettingsTranslator.java
Labels: Bugfix
