Repository GeyserMC/Geyser, pull requests merged in 2020-07, with the labels that each got.

#926 Fix version checking on older Java versions
  connector/src/main/java/org/geysermc/connector/command/defaults/VersionCommand.java
  connector/src/main/java/org/geysermc/connector/utils/WebUtils.java
Labels: Bugfix

#928 Make a copy of the players list when disconnecting them all on shutdown
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
Labels: Bugfix

#927 Fix no gravity falling block entities
  connector/src/main/java/org/geysermc/connector/entity/FallingBlockEntity.java
Labels: Bugfix

#933 Fixed Villager Position when Sleeping
  connector/src/main/java/org/geysermc/connector/entity/living/merchant/VillagerEntity.java
Labels: Bugfix

#932 Add a User-Agent to the rest of the web requests
  connector/src/main/java/org/geysermc/connector/utils/SkinProvider.java
  connector/src/main/java/org/geysermc/connector/utils/WebUtils.java
Labels: Optimization

#936 Check the name tag exists for anvil renaming to prevent an NPE
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/AnvilInventoryTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
Labels: Bugfix, Needs Testing

#945 Add an extra headless check to fix occational errors
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java
Labels: Bugfix, Needs Testing

#947 Update map colors to 1.16
  connector/src/main/java/org/geysermc/connector/utils/MapColor.java
Labels: Bugfix

#955 Allow for returning of error messages
  connector/src/main/java/org/geysermc/connector/utils/WebUtils.java
Labels: Bugfix, Needs Testing

#767 Fix buckets not working on mobile
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemRegistry.java
Labels: Bugfix, Client Workaround

#1021 Fix Wolf anger display
  connector/src/main/java/org/geysermc/connector/entity/living/animal/tameable/WolfEntity.java
Labels: Bugfix, Needs Testing

#1001 Check if the passenger is null before trying to update metadata
  connector/src/main/java/org/geysermc/connector/entity/living/animal/StriderEntity.java
Labels: Bugfix, Needs Testing

#1057 Update closest color conversion
  connector/src/main/java/org/geysermc/connector/utils/MessageUtils.java
Labels: Bugfix

#1022 Only send metadata update once per Java metadata packet
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityMetadataTranslator.java
Labels: Optimization

#1062 Fix clone-remote-port
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
Labels: Bugfix

#685 Small entity metadata fix, other player bow implementation
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/LivingEntity.java
  connector/src/main/java/org/geysermc/connector/entity/living/monster/AbstractSkeletonEntity.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemRegistry.java
Labels: Bugfix
