Repository GeyserMC/Geyser, pull requests merged in 2020-11, with the labels that each got.

#1504 Add config option for enabling achievements
  connector/src/main/java/org/geysermc/connector/configuration/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/resources/config.yml
Labels: Bugfix, Feature

#1446 Fixed some issues related to Scoreboards
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaDisplayScoreboardTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaScoreboardObjectiveTranslator.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Objective.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Score.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Scoreboard.java
  connector/src/main/java/org/geysermc/connector/scoreboard/Team.java
Labels: Bugfix, Optimization

#1498 Rewrite message handling in MessageUtils to use Adventure
  connector/pom.xml
  connector/src/main/java/org/geysermc/connector/entity/CommandBlockMinecartEntity.java
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/ConnectorServerEventHandler.java
  connector/src/main/java/org/geysermc/connector/network/QueryPacketHandler.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/BossBar.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockCommandRequestTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockTextTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MessageTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MinecraftTranslationRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/BasicItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/BookPagesTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaChatTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDisconnectPacket.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaLoginDisconnectTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaTitleTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaScoreboardObjectiveTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaTeamTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/window/JavaOpenWindowTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/entity/CommandBlockBlockEntityTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/entity/SignBlockEntityTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/FileUtils.java
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
  connector/src/main/java/org/geysermc/connector/utils/MessageUtils.java
  connector/src/test/java/org/geysermc/connector/network/translators/chat/MessageTranslatorTest.java
Labels: Bugfix, Needs Testing, Optimization

#1567 Clean-up translation string implementation
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MessageTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MinecraftTranslationRegistry.java
Labels: Optimization

#1574 Fix en_us downloading and hashing on Android
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
Labels: Bugfix

#1575 Another android fix
  connector/src/main/java/org/geysermc/connector/utils/FileUtils.java
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
Labels: Bugfix

#1582 Clear the Reflections scanners to stop it trying to scan
  connector/src/main/java/org/geysermc/connector/utils/FileUtils.java
Labels: Optimization

#1570 Move the "Please wait until you are logged in..." message to the Action Bar
  connector/src/main/java/org/geysermc/connector/network/UpstreamPacketHandler.java
Labels: Feature

#1572 Update MCProtocolLib to Adventure migration
  connector/pom.xml
  connector/src/main/java/org/geysermc/connector/entity/CommandBlockMinecartEntity.java
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/player/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/BossBar.java
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MessageTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaChatTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDisconnectPacket.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaLoginDisconnectTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaTitleTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaScoreboardObjectiveTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/scoreboard/JavaTeamTranslator.java
Labels: Bugfix, Needs Testing

#1602 Add check to fix NONE team color causing an NPE
  connector/src/main/java/org/geysermc/connector/network/translators/chat/MessageTranslator.java
Labels: Bugfix
