Repository GeyserMC/Geyser, pull requests merged in 2020-06, with the labels that each got.

#712 Add furnace minecart
  connector/src/main/java/org/geysermc/connector/entity/FurnaceMinecartEntity.java
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/BlockTranslator.java
Labels: Feature

#716 Fix Ender Crystal collision and explosion effects
  connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaExplosionTranslator.java
Labels: Bugfix, Needs Testing

#717 Fix new minecart with block breaking furnace minecart display
  connector/src/main/java/org/geysermc/connector/entity/FurnaceMinecartEntity.java
  connector/src/main/java/org/geysermc/connector/entity/MinecartEntity.java
Labels: Bugfix

#722 Check for instance of TranslationMessage
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
Labels: Bugfix, Needs Testing

#559 Add item name translation
  connector/src/main/java/org/geysermc/connector/entity/ItemEntity.java
  connector/src/main/java/org/geysermc/connector/entity/ItemFrameEntity.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/PlayerInventoryTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/action/InventoryActionDataTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/updater/ChestInventoryUpdater.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/updater/ContainerInventoryUpdater.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/updater/CursorInventoryUpdater.java
  connector/src/main/java/org/geysermc/connector/network/translators/inventory/updater/InventoryUpdater.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/JavaDeclareRecipesTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityEquipmentTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaSpawnParticleTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/InventoryUtils.java
Labels: Bugfix

#697 Fix position of non-marker invisible armour stands
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/living/ArmorStandEntity.java
Labels: Bugfix, Needs Testing

#736 Fix query not following normal MC standards
  connector/src/main/java/org/geysermc/connector/network/QueryPacketHandler.java
Labels: Bugfix

#678 Relocate Jackson dependency
  bootstrap/bukkit/pom.xml
Labels: Bugfix, On hold

#753 Stop using TrigMath class
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/utils/MathUtils.java
Labels: Optimization

#755 Add ServerPlayerListDataPacket to ignored packets
  connector/src/main/java/org/geysermc/connector/network/translators/PacketTranslatorRegistry.java
Labels: Optimization

#692 Prevent swimming animation from appearing on older servers
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
Labels: Bugfix, Needs Testing

#771 Fix form images
  common/src/main/java/org/geysermc/common/window/button/FormImage.java
Labels: Bugfix

#758 Fix maps not loading in sometimes
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockMapInfoRequestTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/MapItemTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaMapDataTranslator.java
Labels: Bugfix, Needs Testing

#675 Entity (mostly rotation) fixes
  connector/src/main/java/org/geysermc/connector/entity/BoatEntity.java
  connector/src/main/java/org/geysermc/connector/entity/Entity.java
  connector/src/main/java/org/geysermc/connector/entity/PaintingEntity.java
  connector/src/main/java/org/geysermc/connector/entity/PlayerEntity.java
  connector/src/main/java/org/geysermc/connector/entity/living/animal/PigEntity.java
  connector/src/main/java/org/geysermc/connector/entity/living/animal/tameable/CatEntity.java
  connector/src/main/java/org/geysermc/connector/entity/living/merchant/AbstractMerchantEntity.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityHeadLookTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityPositionRotationTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityRotationTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityTeleportTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/spawn/JavaSpawnEntityTranslator.java
Labels: Bugfix, Needs Testing

#768 Add 1.9+ PvP 'Cooldown'
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserConfiguration.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockLevelSoundEventTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockMobEquipmentTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityPropertiesTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/AttributeUtils.java
  connector/src/main/java/org/geysermc/connector/utils/CooldownUtils.java
  connector/src/main/resources/config.yml
Labels: Client Workaround, Feature

#759 Reset color instead of turning color to white for standalone
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneLogger.java
Labels: Bugfix

#777 Fix toggle component json generation
  common/src/main/java/org/geysermc/common/window/component/ToggleComponent.java
Labels: Bugfix

#784 Add a setter to the auth type to allow for changing at runtime
  connector/src/main/java/org/geysermc/connector/GeyserConnector.java
Labels: Feature

#787 Clarify Bedrock remote address change
  connector/src/main/resources/config.yml
Labels: Optimization

#809 Fix en_us locale downloading
  connector/src/main/java/org/geysermc/connector/utils/LocaleUtils.java
Labels: Bugfix, Needs Testing

#808 Add dump command
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeeDumpInfo.java
  bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeePlugin.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotDumpInfo.java
  bootstrap/spigot/src/main/java/org/geysermc/platform/spigot/GeyserSpigotPlugin.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongeDumpInfo.java
  bootstrap/sponge/src/main/java/org/geysermc/platform/sponge/GeyserSpongePlugin.java
  bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneBootstrap.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityDumpInfo.java
  bootstrap/velocity/src/main/java/org/geysermc/platform/velocity/GeyserVelocityPlugin.java
  common/src/main/java/org/geysermc/common/serializer/AsteriskSerializer.java
  connector/pom.xml
  connector/src/main/java/org/geysermc/connector/bootstrap/GeyserBootstrap.java
  connector/src/main/java/org/geysermc/connector/command/CommandManager.java
  connector/src/main/java/org/geysermc/connector/command/defaults/DumpCommand.java
  connector/src/main/java/org/geysermc/connector/configuration/GeyserJacksonConfiguration.java
  connector/src/main/java/org/geysermc/connector/dump/BootstrapDumpInfo.java
  connector/src/main/java/org/geysermc/connector/dump/DumpInfo.java
  connector/src/main/java/org/geysermc/connector/utils/DockerCheck.java
  connector/src/main/java/org/geysermc/connector/utils/WebUtils.java
Labels: Feature
