Repository GeyserMC/Geyser, pull requests merged in 2021-01, with the labels that each got.

#1815 Trigger builds of Geyser-Fabric and GeyserAndroid after a build success
  Jenkinsfile
Labels: Feature, Optimization

#1117 Implement book editing
  connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  connector/src/main/java/org/geysermc/connector/network/session/cache/BookEditCache.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockBookEditTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockMobEquipmentTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockMovePlayerTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/ItemRegistry.java
  connector/src/main/java/org/geysermc/connector/network/translators/item/translators/nbt/BookPagesTranslator.java
Labels: Feature

#1336 Block breaking refactors
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockInventoryTransactionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/bedrock/entity/player/BedrockActionTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityStatusTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/entity/player/JavaPlayerActionAckTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaBlockChangeTranslator.java
  connector/src/main/java/org/geysermc/connector/network/translators/world/block/BlockTranslator.java
  connector/src/main/java/org/geysermc/connector/utils/BlockUtils.java
Labels: Bugfix

#1838 Disable build notifications for sub-builds and build GeyserConnect
  Jenkinsfile
Labels: Feature

#1851 Localize Done in the OAuth prompt
  connector/src/main/java/org/geysermc/connector/utils/LoginEncryptionUtils.java
Labels: Bugfix

#1706 Fix NPE when link entity not found and use non-deprecated constructor
  connector/src/main/java/org/geysermc/connector/entity/player/PlayerEntity.java
Labels: Bugfix, Needs Testing
