Repository GeyserMC/Geyser, pull requests merged in 2021-12, with the labels that each got.

#2667 Improve Statistics Form
  core/pom.xml
  core/src/main/java/org/geysermc/geyser/registry/BlockRegistries.java
  core/src/main/java/org/geysermc/geyser/registry/Registries.java
  core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/util/StatisticFormatters.java
  core/src/main/java/org/geysermc/geyser/util/StatisticsUtils.java
Labels: PR: Bugfix, PR: Cosmetic

#2663 Show the nether fog when using the nether height workaround
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/session/cache/WorldBorder.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
  core/src/main/java/org/geysermc/geyser/util/DimensionUtils.java
  core/src/main/resources/config.yml
Labels: PR: Client Workaround

#2701 Fix some mount offsets and strange behaviors with GSit
  core/src/main/java/org/geysermc/geyser/entity/type/AreaEffectCloudEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/BoatEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/Entity.java
  core/src/main/java/org/geysermc/geyser/entity/type/FishingHookEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/ArmorStandEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/animal/StriderEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/monster/GuardianEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/monster/PiglinEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/monster/WitherEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZoglinEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/monster/ZombieEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/session/cache/EntityCache.java
  core/src/main/java/org/geysermc/geyser/session/cache/TeleportCache.java
  core/src/main/java/org/geysermc/geyser/session/cache/WorldBorder.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockMoveEntityAbsoluteTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockPlayerInputTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockInteractTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockMovePlayerTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockRiderJumpTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaAnimateTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaEntityEventTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityPosRotTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityPosTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveEntityRotTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveVehicleTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRemoveMobEffectTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRotateHeadTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityDataTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityLinkTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEntityMotionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetEquipmentTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetPassengersTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaTakeItemEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaTeleportEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateAttributesTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateMobEffectTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerPositionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/spawn/JavaAddEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/util/EntityUtils.java
Labels: PR: Bugfix

#2728 Fix sneaking speed adjustment and bounding box
  core/src/main/java/org/geysermc/geyser/entity/EntityDefinitions.java
  core/src/main/java/org/geysermc/geyser/entity/type/Entity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockAdventureSettingsTranslator.java
Labels: PR: Bugfix

#2729 fix: Return early if tag is null
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BannerBlockEntityTranslator.java
Labels: PR: Bugfix
