Repository GeyserMC/Geyser, pull requests merged in 2023-08, with the labels that each got.

#4076 Allow srv resolving to be set per remote server
  api/src/main/java/org/geysermc/geyser/api/network/RemoteServer.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Feature, PR: Bugfix

#4079 Fix duplicate extension's help command permission registration on Paper
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.java
  core/src/main/java/org/geysermc/geyser/command/GeyserCommandManager.java
  core/src/main/java/org/geysermc/geyser/command/defaults/HelpCommand.java
Labels: PR: Bugfix, Extensions

#4082 Don't error when skull skin cache doesnt exist
  core/src/main/java/org/geysermc/geyser/pack/SkullResourcePackManager.java
Labels: PR: Bugfix
