Repository GeyserMC/Geyser, pull requests merged in 2023-06, with the labels that each got.

#3834 Handle effects with infinite duration
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateMobEffectTranslator.java
Labels: PR: Bugfix

#3842 Check for null server ip on Fabric
  bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricMod.java
Labels: PR: Bugfix

#3837 Translate armour trims on items
  core/src/main/java/org/geysermc/geyser/item/type/ArmorItem.java
  core/src/main/java/org/geysermc/geyser/item/type/Item.java
Labels: PR: Bugfix

#3841 Update EmotePacket creation for 1.20
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockEmoteTranslator.java
Labels: PR: Bugfix

#3852 Leniency when trimming incoming sound ids
  core/src/main/java/org/geysermc/geyser/util/SoundUtils.java
Labels: PR: Bugfix

#3855 Show archeology brushing animations
  core/src/main/java/org/geysermc/geyser/level/block/BlockStateValues.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BrushableBlockEntityTranslator.java
Labels: PR: Bugfix

#3878 fix commands with trailing whitespaces
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockCommandRequestTranslator.java
Labels: PR: Bugfix

#3884 Loop through item palette versions in ascending order
  core/src/main/java/org/geysermc/geyser/registry/populator/CreativeItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
Labels: PR: Bugfix

#3840 Add SessionJoinEvent and SessionLoginEvent
  api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionJoinEvent.java
  api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionLoginEvent.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockSetLocalPlayerAsInitializedTranslator.java
Labels: Extensions

#3798 Move PlatformType to API and expose it for extensions
  api/src/main/java/org/geysermc/geyser/api/GeyserApi.java
  api/src/main/java/org/geysermc/geyser/api/util/PlatformType.java
  bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePlugin.java
  bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricMod.java
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.java
  bootstrap/sponge/src/main/java/org/geysermc/geyser/platform/sponge/GeyserSpongePlugin.java
  bootstrap/standalone/src/main/java/org/geysermc/geyser/platform/standalone/GeyserStandaloneBootstrap.java
  bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityPlugin.java
  core/src/main/java/org/geysermc/connector/GeyserConnector.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/command/GeyserCommandManager.java
  core/src/main/java/org/geysermc/geyser/command/defaults/ConnectionTestCommand.java
  core/src/main/java/org/geysermc/geyser/command/defaults/DumpCommand.java
  core/src/main/java/org/geysermc/geyser/command/defaults/HelpCommand.java
  core/src/main/java/org/geysermc/geyser/command/defaults/ReloadCommand.java
  core/src/main/java/org/geysermc/geyser/command/defaults/StopCommand.java
  core/src/main/java/org/geysermc/geyser/command/defaults/VersionCommand.java
  core/src/main/java/org/geysermc/geyser/dump/BootstrapDumpInfo.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/PistonBlockEntity.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockCommandRequestTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginDisconnectTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEventTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockUpdateTranslator.java
Labels: PR: Feature, Extensions

#3892 Allow deferred registries to be loaded/set more than once
  core/src/main/java/org/geysermc/geyser/registry/DeferredRegistry.java
Labels: PR: Bugfix

#3894 Validate written_book tags and fix writable book losing changes
  core/src/main/java/org/geysermc/geyser/inventory/item/StoredItemMappings.java
  core/src/main/java/org/geysermc/geyser/item/Items.java
  core/src/main/java/org/geysermc/geyser/item/type/WritableBookItem.java
  core/src/main/java/org/geysermc/geyser/item/type/WrittenBookItem.java
  core/src/main/java/org/geysermc/geyser/session/cache/BookEditCache.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBookEditTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java
Labels: PR: Bugfix

#3898 Fix/proxy protocol missing message
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  core/src/main/java/org/geysermc/geyser/network/netty/proxy/ProxyServerHandler.java
Labels: PR: Bugfix

#3904 Fix serverbound hanging sign updates
  core/src/main/java/org/geysermc/geyser/level/block/BlockStateValues.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java
  core/src/main/java/org/geysermc/geyser/util/SignUtils.java
Labels: PR: Bugfix

#3925 Fix loading contents keys of encrypted resource packs
  core/src/main/java/org/geysermc/geyser/registry/loader/ResourcePackLoader.java
  core/src/test/java/org/geysermc/geyser/registry/loader/ResourcePackLoaderTest.java
  core/src/test/resources/empty_pack.mcpack
  core/src/test/resources/encrypted_pack.zip
  core/src/test/resources/encrypted_pack.zip.key
Labels: PR: Bugfix
