Repository GeyserMC/Geyser, pull requests merged in 2023-09, with the labels that each got.

#3951 make ConnectionTestCommand more foolproof
  core/src/main/java/org/geysermc/geyser/command/defaults/ConnectionTestCommand.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
Labels: PR: Optimization

#4093 Fix forced zoom issue when switching into spectator mode, use new spectator mode
  core/src/main/java/org/geysermc/geyser/entity/type/living/ArmorStandEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaRespawnTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaGameEventTranslator.java
  core/src/main/java/org/geysermc/geyser/util/EntityUtils.java
Labels: PR: Feature, PR: Bugfix

#4066 Fix: Don't send pink actionbar/systemchat messages
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaSystemChatTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/title/JavaSetActionBarTextTranslator.java
Labels: PR: Bugfix

#4106 Update inventory titles in e.g. chest GUIs
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenScreenTranslator.java
Labels: PR: Bugfix

#4062 Feature: Allow client-side "game settings" menu gamemode/difficulty changes
  bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/world/GeyserFabricWorldManager.java
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/manager/GeyserSpigotWorldManager.java
  core/src/main/java/org/geysermc/geyser/level/GeyserWorldManager.java
  core/src/main/java/org/geysermc/geyser/level/WorldManager.java
  core/src/main/java/org/geysermc/geyser/network/LoggingPacketHandler.java
  core/src/main/java/org/geysermc/geyser/registry/PacketTranslatorRegistry.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetDefaultGameTypeTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetDifficultyTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockSetPlayerGameTypeTranslator.java
  core/src/main/java/org/geysermc/geyser/util/SettingsUtils.java
Labels: PR: Feature

#4132 Fix observer directions for 1.20.10+
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4165 Force loading help-text using utf-8 to fix encoding errors
  core/src/main/java/org/geysermc/geyser/GeyserMain.java
Labels: PR: Bugfix, PR: Cosmetic
