Repository GeyserMC/Geyser, pull requests merged in 2023-12, with the labels that each got.

#4232 Clear mob spawners if the Java server so requests
  core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/type/BlockMappings.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SpawnerBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEntityDataTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelChunkWithLightTranslator.java
Labels: PR: Bugfix

#4324 SettingsUtil form optimization, potential fix for issue 4289
  core/src/main/java/org/geysermc/geyser/util/SettingsUtils.java
Labels: PR: Bugfix, PR: Needs review

#4320 Ensure extensions never stop Geyser from starting
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLoader.java
Labels: PR: Bugfix

#4175 Add more info to Fabric's geyser dumps
  bootstrap/fabric/src/main/java/org/geysermc/geyser/platform/fabric/GeyserFabricDumpInfo.java
  core/src/main/java/org/geysermc/geyser/text/AsteriskSerializer.java
Labels: PR: Optimization, PR: Needs review

#2523 Update config.yml
  core/src/main/resources/config.yml
Labels: PR: Feature

#4302 Fix collision problem with glass pane and iron bars
  core/src/main/java/org/geysermc/geyser/translator/collision/GlassPaneAndIronBarsCollision.java
Labels: PR: Bugfix

#4331 Catch UnknownHostExceptions in legacy ping passthrough pings
  core/src/main/java/org/geysermc/geyser/ping/GeyserLegacyPingPassthrough.java
Labels: PR: Bugfix

#4047 Add support for adding custom translations.
  core/src/main/java/org/geysermc/geyser/text/MinecraftLocale.java
Labels: PR: Feature

#4340 Spigot world adapter for 1.20.4
  gradle/libs.versions.toml
Labels: PR: Feature

#4351 Fix (de)serialization of ClientboundExplodePacket
  gradle/libs.versions.toml
Labels: PR: Bugfix
