Repository GeyserMC/Geyser, pull requests merged in 2023-10, with the labels that each got.

#3946 Allow extensions to load other extension's classes, and store extensions by IDs instead of name
  api/src/main/java/org/geysermc/geyser/api/extension/ExtensionManager.java
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.java
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionClassLoader.java
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLoader.java
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionManager.java
Labels: PR: Bugfix, Extensions

#4029 Close threads at server shutdown
  core/src/main/java/org/geysermc/geyser/network/GeyserServerInitializer.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4147 Remove Mojang account sign-in option
  core/src/main/java/org/geysermc/connector/GeyserConnector.java
  core/src/main/java/org/geysermc/connector/network/session/GeyserSession.java
  core/src/main/java/org/geysermc/connector/network/session/auth/AuthData.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserConfiguration.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
  core/src/main/java/org/geysermc/geyser/network/UpstreamPacketHandler.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/util/FileUtils.java
  core/src/main/java/org/geysermc/geyser/util/LoginEncryptionUtils.java
Labels: PR: Under Review

#4183 Tell the server we loaded the resource pack
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaClientboundResourcePacksPacket.java
Labels: PR: Bugfix

#4198 Fix: Flying issues after 1.20.30 due to new PlayerAction cases
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockRequestAbilityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
Labels: PR: Bugfix

#4199 Fix: Beacon effects broken since 1.20.2
  core/src/main/java/org/geysermc/geyser/translator/inventory/BeaconInventoryTranslator.java
Labels: PR: Bugfix

#4197 Fix: Don't rename extension folders while extension directory is being walked
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLoader.java
Labels: PR: Bugfix

#4200 Fix: Skull rotation issues since 1.20.2
  core/src/main/java/org/geysermc/geyser/level/block/BlockStateValues.java
Labels: PR: Bugfix

#4207 Fixed incorrect bedrock version of skin mirroring geometry
  core/src/main/resources/bedrock/skin/geometry.humanoid.wearingCustomSkull.json
  core/src/main/resources/bedrock/skin/geometry.humanoid.wearingCustomSkullSlim.json
Labels: PR: Bugfix

#4211 Fall back to default secure random on all platforms
  common/src/main/java/org/geysermc/floodgate/crypto/AesKeyProducer.java
Labels: PR: Bugfix
