Repository GeyserMC/Geyser, pull requests merged in 2024-04, with the labels that each got.

#4532 Allow configuration of RakNet limits
  core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  core/src/main/java/org/geysermc/geyser/util/FileUtils.java
  core/src/main/java/org/geysermc/geyser/util/WebUtils.java
  core/src/main/resources/config.yml
  gradle/libs.versions.toml
Labels: PR: Feature

#4533 Add ConnectionRequestEvent
  api/src/main/java/org/geysermc/geyser/api/event/connection/ConnectionRequestEvent.java
  bootstrap/mod/fabric/build.gradle.kts
  bootstrap/mod/neoforge/build.gradle.kts
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  gradle.properties
Labels: PR: Feature

#4539 Ensure proxiedAddresses is not null before lookup
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
Labels: PR: Bugfix

#4540 Fix block custom registration failing with simmilar named items
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomBlockRegistryPopulator.java
Labels: PR: Bugfix

#4542 Fix CreativeCategory enum numbers
  api/src/main/java/org/geysermc/geyser/api/util/CreativeCategory.java
Labels: PR: Bugfix

#4549 Update CreativeCategory none to have the correct value
  api/src/main/java/org/geysermc/geyser/api/util/CreativeCategory.java
Labels: PR: Bugfix

#4557 Fix bug when breaking head blocks added by Polymer mods
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockDestructionTranslator.java
Labels: PR: Bugfix

#4562 Fix user agent strings
  core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java
  core/src/main/java/org/geysermc/geyser/util/WebUtils.java
Labels: PR: Bugfix

#4554 Support RakNet Cookies
  build-logic/src/main/kotlin/geyser.modded-conventions.gradle.kts
  core/build.gradle.kts
  core/src/main/java/org/geysermc/geyser/dump/DumpInfo.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: PR: Needs Testing, PR: Feature

#4521 Feature: Structure block translation
  README.md
  core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/type/BlockMappings.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/session/cache/StructureBlockCache.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/StructureBlockBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockStructureBlockUpdateTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockStructureTemplateDataRequestTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEntityDataTranslator.java
  core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
  core/src/main/java/org/geysermc/geyser/util/StructureBlockUtils.java
Labels: PR: Feature, PR: Needs review

#4576 Remove map cache
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockMapInfoRequestTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaMapItemDataTranslator.java
Labels: PR: Bugfix

#4566 Reset metadata and attributes if needed when respawning
  core/src/main/java/org/geysermc/geyser/entity/attribute/GeyserAttributeType.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaRespawnTranslator.java
Labels: PR: Bugfix

#4579 Fix: Properly check whether the `so_reuseport` socket option is available
  bootstrap/bungeecord/build.gradle.kts
  bootstrap/spigot/build.gradle.kts
  bootstrap/velocity/build.gradle.kts
  bootstrap/viaproxy/build.gradle.kts
  build-logic/src/main/kotlin/geyser.modded-conventions.gradle.kts
  core/build.gradle.kts
  core/src/main/java/org/geysermc/geyser/network/netty/Bootstraps.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  gradle/libs.versions.toml
Labels: PR: Bugfix
