Repository GeyserMC/Geyser, pull requests merged in 2024-06, with the labels that each got.

#4705 Feature: Add API to show/hide GUI elements
  api/src/main/java/org/geysermc/geyser/api/bedrock/camera/CameraData.java
  api/src/main/java/org/geysermc/geyser/api/bedrock/camera/GuiElement.java
  core/src/main/java/org/geysermc/geyser/impl/camera/GeyserCameraData.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  gradle.properties
Labels: PR: Feature, PR: Cosmetic

#4719 Ignore PurchaseReceiptPacket instead of kicking players
  core/src/main/java/org/geysermc/geyser/network/CodecProcessor.java
Labels: PR: Bugfix

#4746 Catch EOFExceptions when the remote server is misconfigured/not online
  core/src/main/java/org/geysermc/geyser/ping/GeyserLegacyPingPassthrough.java
Labels: PR: Bugfix

#4731 Partially implement handling of "hide_tooltip" and fix attribute modifiers in "Armor" category not showing
  core/src/main/java/org/geysermc/geyser/item/type/Item.java
  core/src/main/java/org/geysermc/geyser/translator/item/ItemTranslator.java
Labels: PR: Bugfix

#4762 Sanity check for shulker boxes
  core/src/main/java/org/geysermc/geyser/level/block/type/BlockState.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/ShulkerBoxBlockEntityTranslator.java
Labels: PR: Bugfix

#4761 Fix: readme not being synched to modrinth
  .github/workflows/build.yml
  bootstrap/bungeecord/build.gradle.kts
  bootstrap/mod/build.gradle.kts
  bootstrap/mod/fabric/build.gradle.kts
  bootstrap/mod/neoforge/build.gradle.kts
  bootstrap/spigot/build.gradle.kts
  bootstrap/velocity/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/LibsAccessor.kt
  build-logic/src/main/kotlin/geyser.modded-conventions.gradle.kts
  build-logic/src/main/kotlin/geyser.modrinth-uploading-conventions.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4770 Feat: Add changelog to modrinth releases
  .github/workflows/build.yml
  build-logic/src/main/kotlin/geyser.modrinth-uploading-conventions.gradle.kts
Labels: PR: Feature, PR: Cosmetic

#4766 Fix: Ignore invalid block entity data sent by Java server
  api/src/main/java/org/geysermc/geyser/api/block/custom/nonvanilla/JavaBlockState.java
  core/src/main/java/org/geysermc/geyser/level/block/Blocks.java
  core/src/main/java/org/geysermc/geyser/level/block/GeyserJavaBlockState.java
  core/src/main/java/org/geysermc/geyser/level/block/type/Block.java
  core/src/main/java/org/geysermc/geyser/level/block/type/BlockState.java
  core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/BrushableBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/DecoratedPotBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/DoubleChestBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/ShulkerBoxBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SkullBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/SpawnerBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/StructureBlockBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/TrialSpawnerBlockEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEntityDataTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelChunkWithLightTranslator.java
Labels: PR: Bugfix

#4771 Fix build errors reporting to the wrong directory by updating blossom
  core/build.gradle.kts
  core/src/main/java-templates/org/geysermc/geyser/BuildData.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4704 Fix: Bedrock players dying of fall damage, instead of falling in the void
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockMovePlayerTranslator.java
Labels: PR: Bugfix, PR: Needs review

#4336 Show build number in startup log and version check command
  core/build.gradle.kts
  core/src/main/java-templates/org/geysermc/geyser/BuildData.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/command/defaults/VersionCommand.java
Labels: PR: Feature, PR: Cosmetic
