Repository GeyserMC/Geyser, pull requests merged in 2024-03, with the labels that each got.

#4470 Deprecate unit cube in block components
  api/src/main/java/org/geysermc/geyser/api/block/custom/component/CustomBlockComponents.java
  core/src/main/java/org/geysermc/geyser/level/block/GeyserCustomBlockComponents.java
  core/src/main/java/org/geysermc/geyser/registry/mappings/versions/MappingsReader_v1.java
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomBlockRegistryPopulator.java
Labels: PR: Bugfix

#4471 Fix lecterns on 1.20.60, add support for virtual books
  core/src/main/java/org/geysermc/geyser/inventory/holder/BlockInventoryHolder.java
  core/src/main/java/org/geysermc/geyser/inventory/item/StoredItemMappings.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/inventory/LecternInventoryTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockInventoryTransactionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockLecternUpdateTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockInteractTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerSetContentTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerSetSlotTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenBookTranslator.java
  core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
Labels: PR: Feature, PR: Bugfix

#4473 Update ViaVersion api usage
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.java
Labels: PR: Dependency

#4456 update workflow file to node20
  .github/workflows/build.yml
  .github/workflows/pullrequest.yml
Labels: PR: Dependency

#4480 Add new village map icons
  core/src/main/java/org/geysermc/geyser/level/BedrockMapIcon.java
Labels: PR: Feature

#3530 Cap render distance at 96
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Bugfix

#4484 Fix: Allow adding custom items to the creative item list to allow custom recipes to show up in the recipe book
  api/src/main/java/org/geysermc/geyser/api/block/custom/CustomBlockData.java
  api/src/main/java/org/geysermc/geyser/api/item/custom/CustomItemData.java
  api/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/item/GeyserCustomItemData.java
  core/src/main/java/org/geysermc/geyser/item/GeyserNonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/registry/mappings/versions/MappingsReader_v1.java
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Feature, PR: Bugfix, PR: Needs review

#4494 Fix virtual lecterns again, lol
  core/src/main/java/org/geysermc/geyser/inventory/LecternContainer.java
  core/src/main/java/org/geysermc/geyser/translator/inventory/LecternInventoryTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenBookTranslator.java
Labels: PR: Needs Testing, PR: Bugfix

#4496 More error-robust kernel version parsing
  core/src/main/java/org/geysermc/geyser/network/netty/Bootstraps.java
Labels: PR: Bugfix

#4499 Fix: Inventory handling when client tries to open the player inventory when it shouldn't
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockInteractTranslator.java
Labels: PR: Needs Testing, PR: Bugfix

#4495 Allow custom tools to show an attack damage
  api/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/item/GeyserNonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/item/Items.java
  core/src/main/java/org/geysermc/geyser/item/components/ToolTier.java
  core/src/main/java/org/geysermc/geyser/item/type/Item.java
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java
Labels: Priority: Low, PR: Cosmetic

#4512 Update Jackson
  bootstrap/velocity/build.gradle.kts
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionDescription.java
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4522 Fix entity pick request for cherry and bamboo boats
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockEntityPickRequestTranslator.java
Labels: PR: Bugfix

#4530 Allow NonVanillaCustomItemData to have a block assigned
  api/src/main/java/org/geysermc/geyser/api/item/custom/NonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/item/GeyserNonVanillaCustomItemData.java
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java
Labels: PR: Feature
