Repository GeyserMC/Geyser, pull requests merged in 2024-01, with the labels that each got.

#4399 Fix: Geyser-Velocity compression disabler due to packet name changes
  bootstrap/velocity/src/main/java/org/geysermc/geyser/platform/velocity/GeyserVelocityCompressionDisabler.java
Labels: PR: Bugfix

#4387 Don't try to show the server settings form to players who are not logged in
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockServerSettingsRequestTranslator.java
Labels: PR: Bugfix

#4168 Add fetching MC versions and Console from the extensions API
  api/src/main/java/org/geysermc/geyser/api/GeyserApi.java
  api/src/main/java/org/geysermc/geyser/api/util/MinecraftVersion.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/impl/MinecraftVersionImpl.java
  gradle.properties
Labels: PR: Feature, API, PR: Needs review

#4293 Feature: Allow setting a different port in the motd
  api/src/main/java/org/geysermc/geyser/api/network/BedrockListener.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/command/defaults/ConnectionTestCommand.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserConfiguration.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
  core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java
  core/src/main/resources/config.yml
Labels: PR: Feature, PR: Needs review

#4412 Fix language key typo when floodgate encryption fails
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Bugfix
