Repository GeyserMC/Geyser, pull requests merged in 2024-05, with the labels that each got.

#4604 Feat: Make connection data exposed in api less prone to throw errors
  api/src/main/java/org/geysermc/geyser/api/event/connection/ConnectionRequestEvent.java
  core/src/main/java/org/geysermc/geyser/network/GeyserServerInitializer.java
  core/src/main/java/org/geysermc/geyser/network/UpstreamPacketHandler.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Bugfix, API

#4651 Ensure we load mod resources correctly on Geyser-NeoForge
  bootstrap/mod/neoforge/build.gradle.kts
  bootstrap/mod/neoforge/src/main/java/org/geysermc/geyser/platform/neoforge/GeyserNeoForgeBootstrap.java
  bootstrap/mod/neoforge/src/main/java/org/geysermc/geyser/platform/neoforge/GeyserNeoForgePlatform.java
Labels: PR: Bugfix

#4507 Remove unofficial skin sources and add skin event for extensions
  .idea/copyright/Geyser.xml
  api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionSkinApplyEvent.java
  api/src/main/java/org/geysermc/geyser/api/skin/Cape.java
  api/src/main/java/org/geysermc/geyser/api/skin/Skin.java
  api/src/main/java/org/geysermc/geyser/api/skin/SkinData.java
  api/src/main/java/org/geysermc/geyser/api/skin/SkinGeometry.java
  core/src/main/java/org/geysermc/geyser/configuration/GeyserConfiguration.java
  core/src/main/java/org/geysermc/geyser/pack/SkullResourcePackManager.java
  core/src/main/java/org/geysermc/geyser/skin/FakeHeadProvider.java
  core/src/main/java/org/geysermc/geyser/skin/ProvidedSkins.java
  core/src/main/java/org/geysermc/geyser/skin/SkinManager.java
  core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java
  core/src/main/java/org/geysermc/geyser/skin/SkullSkinManager.java
  core/src/main/resources/bedrock/skin/geometry.humanoid.ears.json
  core/src/main/resources/bedrock/skin/geometry.humanoid.earsSlim.json
  core/src/main/resources/config.yml
  gradle.properties
Labels: PR: Feature

#4663 Fix SessionSkinApplyEvent not keeping altered skin data
  core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java
Labels: PR: Bugfix

#4670 Various entity fixes: Ensure TNT doesn't bug into the ground, reset player entity flags properly
  core/src/main/java/org/geysermc/geyser/entity/EntityDefinitions.java
  core/src/main/java/org/geysermc/geyser/entity/type/Entity.java
  core/src/main/java/org/geysermc/geyser/entity/type/ExpOrbEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/TNTEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/PlayerEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
Labels: PR: Bugfix

#4667 Fix: curly brackets in custom translation strings not being parsed correctly
  core/src/main/java/org/geysermc/geyser/text/MinecraftTranslationRegistry.java
Labels: PR: Bugfix

#4673 Resolve issue when trying to transfer a Geyser player
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4665 Open advancement tab regardless of currently open tab
  core/src/main/java/org/geysermc/geyser/session/cache/AdvancementsCache.java
Labels: PR: Bugfix

#4690 Make allow-third-party-capes default to false
  core/src/main/java/org/geysermc/geyser/configuration/GeyserJacksonConfiguration.java
Labels: PR: Bugfix

#4695 Yeet lectern cache
  bootstrap/mod/src/main/java/org/geysermc/geyser/platform/mod/world/GeyserModWorldManager.java
  bootstrap/spigot/src/main/java/org/geysermc/geyser/platform/spigot/world/manager/GeyserSpigotWorldManager.java
  core/src/main/java/org/geysermc/geyser/level/GeyserWorldManager.java
  core/src/main/java/org/geysermc/geyser/level/WorldManager.java
  core/src/main/java/org/geysermc/geyser/level/block/type/Block.java
  core/src/main/java/org/geysermc/geyser/level/block/type/BlockState.java
  core/src/main/java/org/geysermc/geyser/level/block/type/LecternBlock.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/inventory/LecternInventoryTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaForgetLevelChunkTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaLevelChunkWithLightTranslator.java
  core/src/main/java/org/geysermc/geyser/util/DimensionUtils.java
  core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
Labels: PR: Optimization
