Repository GeyserMC/Geyser, pull requests merged in 2024-08, with the labels that each got.

#4568 Add advancement progress tracker (#4364)
  core/src/main/java/org/geysermc/geyser/level/GeyserAdvancement.java
  core/src/main/java/org/geysermc/geyser/session/cache/AdvancementsCache.java
Labels: PR: Feature

#4930 Allow dumps to be created even if GeyserServer failed to start
  core/src/main/java/org/geysermc/geyser/command/defaults/DumpCommand.java
  core/src/main/java/org/geysermc/geyser/dump/DumpInfo.java
Labels: PR: Bugfix

#4953 Unify repository definition
  build-logic/src/main/kotlin/geyser.build-logic.gradle.kts
  build-logic/src/main/kotlin/geyser.modded-conventions.gradle.kts
  settings.gradle.kts
Labels: PR: Optimization

#4943 Bump minecraftauth
  gradle/libs.versions.toml
Labels: PR: Dependency

#4957 Feature: Add method to close forms in the API
  api/src/main/java/org/geysermc/geyser/api/connection/GeyserConnection.java
  core/src/main/java/org/geysermc/geyser/network/GameProtocol.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: API

#4648 Emulate client side vehicle movement
  core/src/main/java/org/geysermc/geyser/entity/EntityDefinitions.java
  core/src/main/java/org/geysermc/geyser/entity/type/LivingEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/animal/PigEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/animal/StriderEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/living/animal/horse/CamelEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/player/SessionPlayerEntity.java
  core/src/main/java/org/geysermc/geyser/entity/vehicle/BoostableVehicleComponent.java
  core/src/main/java/org/geysermc/geyser/entity/vehicle/CamelVehicleComponent.java
  core/src/main/java/org/geysermc/geyser/entity/vehicle/ClientVehicle.java
  core/src/main/java/org/geysermc/geyser/entity/vehicle/VehicleComponent.java
  core/src/main/java/org/geysermc/geyser/inventory/PlayerInventory.java
  core/src/main/java/org/geysermc/geyser/inventory/item/StoredItemMappings.java
  core/src/main/java/org/geysermc/geyser/level/JavaDimension.java
  core/src/main/java/org/geysermc/geyser/level/block/BlockStateValues.java
  core/src/main/java/org/geysermc/geyser/level/block/Fluid.java
  core/src/main/java/org/geysermc/geyser/level/physics/BoundingBox.java
  core/src/main/java/org/geysermc/geyser/level/physics/CollisionManager.java
  core/src/main/java/org/geysermc/geyser/level/physics/Direction.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/session/cache/PistonCache.java
  core/src/main/java/org/geysermc/geyser/session/cache/WorldBorder.java
  core/src/main/java/org/geysermc/geyser/translator/collision/BlockCollision.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/PistonBlockEntity.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockPlayerInputTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockMovePlayerTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockRiderJumpTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaRespawnTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaMoveVehicleTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaRemoveMobEffectTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaSetPassengersTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaTeleportEntityTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaUpdateMobEffectTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaSetTimeTranslator.java
  gradle/libs.versions.toml
Labels: PR: Needs Testing, PR: Needs review

#4969 Fix: Invalid heads blocking inventory transactions
  core/src/main/java/org/geysermc/geyser/skin/FakeHeadProvider.java
  core/src/main/java/org/geysermc/geyser/translator/item/ItemTranslator.java
Labels: PR: Bugfix

#4989 Feature: Modrinth version names
  build-logic/src/main/kotlin/extensions.kt
  build-logic/src/main/kotlin/geyser.modded-conventions.gradle.kts
  build-logic/src/main/kotlin/geyser.modrinth-uploading-conventions.gradle.kts
  core/build.gradle.kts
Labels: PR: Cosmetic

#4993 Fix moving items from output slot over multiple actions
  core/src/main/java/org/geysermc/geyser/inventory/click/ClickPlan.java
  core/src/main/java/org/geysermc/geyser/translator/inventory/InventoryTranslator.java
Labels: PR: Bugfix

#4999 Fix: Structure blocks/voids in recipes
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
Labels: PR: Bugfix
