Repository GeyserMC/Geyser, pull requests merged in 2024-07, with the labels that each got.

#4815 Fix toggleable block opening sounds (doors, trapdoors, fence gates)
  core/src/main/java/org/geysermc/geyser/level/block/type/DoorBlock.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockUpdateTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/BlockSoundInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/BucketSoundInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/ComparatorSoundInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/FlintAndSteelInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/GrassPathInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/HoeInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/LeverSoundInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/sound/block/OpenableSoundInteractionTranslator.java
  core/src/main/java/org/geysermc/geyser/util/SoundUtils.java
Labels: PR: Bugfix

#4820 Update to loom 1.7-SNAPSHOT, update gradle wrapper
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: PR: Dependency

#4676 Fixed TextDisplay's offsets.
  core/src/main/java/org/geysermc/geyser/entity/EntityDefinitions.java
  core/src/main/java/org/geysermc/geyser/entity/type/DisplayBaseEntity.java
  core/src/main/java/org/geysermc/geyser/entity/type/TextDisplayEntity.java
  core/src/main/java/org/geysermc/geyser/util/EntityUtils.java
Labels: PR: Bugfix

#4822 Show potions & custom items in the shulker box tooltip
  core/src/main/java/org/geysermc/geyser/item/type/ShulkerBoxItem.java
  core/src/main/java/org/geysermc/geyser/translator/item/BedrockItemBuilder.java
Labels: PR: Bugfix

#4131 Add a /geyser ping command
  api/src/main/java/org/geysermc/geyser/api/connection/GeyserConnection.java
  core/src/main/java/org/geysermc/geyser/command/CommandRegistry.java
  core/src/main/java/org/geysermc/geyser/command/defaults/PingCommand.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
Labels: PR: Feature, API

#4814 Fix: hanging sign recipe not showing up in the recipe book
  core/src/main/java/org/geysermc/geyser/registry/populator/CreativeItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
Labels: PR: Bugfix

#4763 Fix: Item color names/glint for rare items
  core/src/main/java/org/geysermc/geyser/item/Items.java
  core/src/main/java/org/geysermc/geyser/item/components/Rarity.java
  core/src/main/java/org/geysermc/geyser/item/type/Item.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/translator/item/ItemTranslator.java
Labels: PR: Feature, PR: Bugfix

#4861 Fix: Close containers that could not be opened
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenBookTranslator.java
  core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
Labels: PR: Bugfix

#4860 Fix: Totem animation for manually played totem effects
  core/src/main/java/org/geysermc/geyser/inventory/PlayerInventory.java
  core/src/main/java/org/geysermc/geyser/inventory/item/StoredItemMappings.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/JavaEntityEventTranslator.java
  core/src/main/java/org/geysermc/geyser/util/InventoryUtils.java
Labels: PR: Bugfix

#4819 Feature: API to switch items in the offhand/mainhand
  api/src/main/java/org/geysermc/geyser/api/entity/EntityData.java
  core/src/main/java/org/geysermc/geyser/entity/GeyserEntityData.java
Labels: API

#4859 Fix: Block place sounds on mod platforms
  bootstrap/mod/src/main/java/org/geysermc/geyser/platform/mod/mixin/server/BlockPlaceMixin.java
  bootstrap/mod/src/main/resources/geyser.mixins.json
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockUpdateTranslator.java
Labels: PR: Bugfix

#4858 Add Timeout to CompletableFuture in GeyserBungeePingPassthrough to Prevent Memory Leak
  bootstrap/bungeecord/src/main/java/org/geysermc/geyser/platform/bungeecord/GeyserBungeePingPassthrough.java
  core/src/main/java/org/geysermc/geyser/ping/IGeyserPingPassthrough.java
Labels: PR: Bugfix

#4847 Empty player list on phase transition, despawn skulls, always reset weather
  core/src/main/java/org/geysermc/geyser/session/cache/EntityCache.java
  core/src/main/java/org/geysermc/geyser/session/cache/SkullCache.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaFinishConfigurationPacketTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java
  core/src/main/java/org/geysermc/geyser/util/DimensionUtils.java
Labels: PR: Bugfix

#4872 Properly fix hanging sign recipes
  core/src/main/java/org/geysermc/geyser/registry/populator/CreativeItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/populator/ItemRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/registry/type/ItemMapping.java
Labels: PR: Bugfix

#4825 Use the correct way of sending block breaking particles
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/entity/player/BedrockActionTranslator.java
Labels: PR: Bugfix

#4873 Somewhat fix: firework recipe not showing up in recipe book
  core/src/main/java/org/geysermc/geyser/item/type/BedrockRequiresTagItem.java
  core/src/main/java/org/geysermc/geyser/item/type/FireworkRocketItem.java
  core/src/main/java/org/geysermc/geyser/translator/item/ItemTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java
Labels: PR: Bugfix

#4885 Fix: Allow custom items to be hats if their Java items also are
  core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java
Labels: PR: Bugfix

#4553 Update DeviceOs to latest protocol
  common/src/main/java/org/geysermc/floodgate/util/DeviceOs.java
Labels: PR: Cosmetic

#4891 Fix: Sticky pistons not retracting on Geyser-Spigot, or visual glitches on other platforms
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEventTranslator.java
Labels: PR: Bugfix

#4779 Port to MinecraftAuth
  bootstrap/mod/fabric/build.gradle.kts
  core/build.gradle.kts
  core/src/main/java/org/geysermc/geyser/Constants.java
  core/src/main/java/org/geysermc/geyser/GeyserImpl.java
  core/src/main/java/org/geysermc/geyser/item/type/PlayerHeadItem.java
  core/src/main/java/org/geysermc/geyser/level/block/type/SkullBlock.java
  core/src/main/java/org/geysermc/geyser/network/UpstreamPacketHandler.java
  core/src/main/java/org/geysermc/geyser/session/GeyserSession.java
  core/src/main/java/org/geysermc/geyser/session/PendingMicrosoftAuthentication.java
  core/src/main/java/org/geysermc/geyser/skin/FakeHeadProvider.java
  core/src/main/java/org/geysermc/geyser/translator/item/ItemTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockSetLocalPlayerAsInitializedTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaGameProfileTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/entity/player/JavaPlayerInfoUpdateTranslator.java
  core/src/main/java/org/geysermc/geyser/util/LoginEncryptionUtils.java
  core/src/main/java/org/geysermc/geyser/util/MinecraftAuthLogger.java
  gradle/libs.versions.toml
Labels: PR: Needs Testing

#4904 Fix: Bedrock players being able to always eat food while in peaceful difficulty
  core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockServerSettingsRequestTranslator.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaChangeDifficultyTranslator.java
  core/src/main/java/org/geysermc/geyser/util/SettingsUtils.java
Labels: PR: Bugfix

#4899 Fix: Piston listener on Fabric/NeoForge
  bootstrap/mod/build.gradle.kts
  bootstrap/mod/src/main/java/org/geysermc/geyser/platform/mod/mixin/server/PistonBaseBlockMixin.java
  bootstrap/mod/src/main/resources/geyser.mixins.json
  core/src/main/java/org/geysermc/geyser/registry/populator/BlockRegistryPopulator.java
  core/src/main/java/org/geysermc/geyser/translator/level/block/entity/PistonBlockEntity.java
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/level/JavaBlockEventTranslator.java
  gradle/libs.versions.toml
Labels: PR: Bugfix

#4917 Update links in README
  README.md
Labels: PR: Cosmetic

#4894 Allow commands with xbox achievements enabled
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaCommandsTranslator.java
  core/src/main/resources/config.yml
Labels: PR: Feature

#4925 Fix: Only add a tag to the bedrock item recipe if it is needed
  core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaUpdateRecipesTranslator.java
Labels: PR: Bugfix

#3880 Fix: Extensions should specify geyser api version instead of base api version
  api/build.gradle.kts
  api/src/main/java-templates/org.geysermc.geyser.api/BuildData.java
  api/src/main/java/org/geysermc/geyser/api/GeyserApi.java
  api/src/main/java/org/geysermc/geyser/api/extension/ExtensionDescription.java
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionDescription.java
  core/src/main/java/org/geysermc/geyser/extension/GeyserExtensionLoader.java
  gradle.properties
  gradle/libs.versions.toml
Labels: Extensions, API
